all: Makefiles
	(cd bm;  make install)
	(cd fo;  make install)
	(cd kn;  make install)
	(cd sm;  make install)

Makefiles:
	(cd bm;  xmkmf)
	(cd fo;  xmkmf)
	(cd kn;  xmkmf)
	(cd sm;  xmkmf)

clean:
	(cd bm;  make clean)
	(cd fo;  make clean)
	(cd kn;  make clean)
	(cd sm;  make clean)

distclean:
	(cd bm;  make distclean)
	(cd fo;  make distclean)
	(cd kn;  make distclean)
	(cd sm;  make distclean)
