#!/bin/sh
set -v
#--
#  Specify job parameters.
#--
sqrts=300.
#sgeb=0.0005
sgeb=0.0035
#sgeb=0.005
isrb=3
ibtp=33
#        ibtp  = 31 : JLC-I S 300
#              = 32 : JLC-I C 300
#              = 33 : JLC-I X 300
#              = 34 : JLC-I S 500
#              = 35 : JLC-I C 500
#              = 36 : JLC-I X 500
#--
#  Specify the executalbe.
#--
dir=..
todir=.
program=fullgen
outfile=bases
#--
#  Go.
#--
$dir/$program.exe << eof > $todir/$outfile.out
@!                                                                      
@!*************************************************                     
@! Input section for Steering part.                                     
@!*************************************************                     
@!                                                                      
STEERING
   EVENT GEN(20)             ! Number of event is just a dummy
*  STEERING DEBUG(37)        ! Standard debug level
   ANAL  SEQ(BASES)          ! Select only BASES module
*  ANAL  SEQ(SPRING LUND_Frag GENE_LIST SWIMMER SMEARING)
   OUTFILE FILE($todir/$outfile.tbs) ! Output file for BASES data
EXIT
@!                                                                      
@!*************************************************                     
@! Input section for Spring part.                                       
@!*************************************************                     
@!                                                                      
BASES
  HELP    !  for PRINT command help
  GETB 0  !  (0,1,2)=(Do BS,Read from TBS,Read from FT23)
  PUTB 1  !  (0,1,2)=(No BS,BS to TBS,BS to FT23)
  DOSP 0  !  (0,1)=(No SP,SP)
  PHST 1  !  (0,1)=(No Hist,Hist)
  PINF 1  !  (0,1)=(No Print,Print)
  PLOG 1  !  (0,1)=(Np Print,Print) BS info
  HSTF $todir/$outfile.tdr ! histogram file
@!  INF  ft23.bs ! input file  for GETB=2
@!  OUTF ft23.bs ! output file for PUTB=2
@!
@! Bases Integration Parameters
@!
  NCAL 400000 !  NCALL
  ITM1 5      !  ITMAX1
  ITM2 10     !  ITMAX2
@!
@! Beam parameters
@!
  ECM  $sqrts ! sqrt(s)
  SGEB $sgeb  ! beam energy spread (fraction)
  ISRB $isrb  ! (1,2,3)=(None,ISR,ISR+BM)
  IBTP $ibtp  ! beamstrahlung type
EXIT                                        
@!                                                                      
@!*************************************************                     
@! Start execution.                                                     
@!*************************************************                     
@!                                                                      
GO
eof
exit 0  
