      COMMON /SSCUPL/ GNCW, GCCZ, GNNZ,
     .                GCESNL, GCNSEL, GCNSER,
     .                GCUSDL, GCUSDR, GCDSUL, GCDSUR,
     .                GNNSNL, GNESEL, GNESER,
     .                GNUSUL, GNUSUR, GNDSDL, GNDSDR
C--
      COMPLEX*8  GNCW(2,4,2), GCCZ(2,2,2), GNNZ(2,4,4)
      COMPLEX*8  GCESNL(2,2), GCNSEL(2,2), GCNSER(2,2),
     .           GCUSDL(2,2), GCUSDR(2,2), GCDSUL(2,2), GCDSUR(2,2)
      COMPLEX*8  GNNSNL(2,4), GNESEL(2,4), GNESER(2,4),
     .           GNUSUL(2,4), GNUSUR(2,4), GNDSDL(2,4), GNDSDR(2,4)
C--
