      COMMON /SSCUPL/ GNCW, GCCZ, GNNZ,
     .                GCESNL, GCNSEL, GCNSER,
     .                GCUSDL, GCUSDR, GCDSUL, GCDSUR,
     .                GNNSNL, GNESEL, GNESER,
     .                GNUSUL, GNUSUR, GNDSDL, GNDSDR,
     .                GCCH,GCNH,GNNH
C--
      COMPLEX*16 GCCH(2,2,2,3), GCNH(2,2,4),GNNH(2,4,4,3)
      COMPLEX*16 GNCW(2,4,2), GCCZ(2,2,2), GNNZ(2,4,4)
      COMPLEX*16 GCESNL(2,2), GCNSEL(2,2), GCNSER(2,2),
     .           GCUSDL(2,2), GCUSDR(2,2), GCDSUL(2,2), GCDSUR(2,2)
      COMPLEX*16 GNNSNL(2,4), GNESEL(2,4), GNESER(2,4),
     .           GNUSUL(2,4), GNUSUR(2,4), GNDSDL(2,4), GNDSDR(2,4)
C--
      COMMON /SSCPL3/ GCSNL3,GCNSE1,GCNSE2,
     .                GCUSD1,GCUSD2,GCDSU1,GCDSU2,
     .                GNSNL3,GNESE1,GNESE2,
     .                GNUSU1,GNUSU2,GNDSD1,GNDSD2 
C--
      COMPLEX*16 GCSNL3(2,2), GCNSE1(2,2), GCNSE2(2,2),
     .           GCUSD1(2,2), GCUSD2(2,2), GCDSU1(2,2), GCDSU2(2,2)
      COMPLEX*16 GNSNL3(2,4), GNESE1(2,4), GNESE2(2,4),
     .           GNUSU1(2,4), GNUSU2(2,4), GNDSD1(2,4), GNDSD2(2,4)
C--
