C* (Contents)
C*    ALFI  : (R*4) : 1/alpha(m_Z).
C*    ALFS  : (R*4) : alpha_s(m_Z).
C*    AMSW  : (R*4) : m_W (GeV).
C*    AMSZ  : (R*4) : m_Z (GeV).
C*    AMSH  : (R*4) : m_H (GeV).
C*    AMST  : (R*4) : m_t (GeV).
C*
C* (Update Record)
C*   95/03/16  K.Fujii		Original version.
C*
      COMMON /USMPRM/  ALFI, ALFS, AMSW, AMSZ, AMSH, AMST
      REAL*4           ALFI, ALFS, AMSW, AMSZ, AMSH, AMST
C=    DATA    ALFI  /  128.0 /
C=    DATA    ALFS  /  0.120 /
C=    DATA    AMSW  /  80.00 /
C=    DATA    AMSZ  /  91.17 /
C=    DATA    AMSH  /  300.0 /
C=    DATA    AMST  /  170.0 /
