#!/bin/bash
# Run Jupiter
# 

jsf -b -q -conf=jsf.conf --maxevt=10 \
   --simtype=3 \
   --runmode=0 \
   --macro=J4UserAnalysis.C \
   --InputFile=xcxcGenBS500.root \
   --OutputFile=jsfj4.root \
   gui.C 

