#!/bin/sh
set -x
#--
#  Set ISRB falg.
#--
title="All"
isrb=2
amt=175
#--
#  Start bases.
#    for m_H = 100
#--
amh=100
echo "new frame" > integ.dat
echo "set limits x 400 1000 y 0 4" >> integ.dat
echo "set order x y 1000 dy 1000 dummy dummy" >> integ.dat
echo "(  $title" >> integ.dat
echo "(  isrb = $isrb" >> integ.dat
echo "(  sqrts	sigma	    error	m_t	     m_H" >> integ.dat
echo "(-----------------------------------------------------------" >> integ.dat
echo "(  m_H = $amh" >> integ.dat
./go_command $amt $amh $((2*$amt+$amh+1))  $isrb
./go_command $amt $amh $((2*$amt+$amh+5))  $isrb
./go_command $amt $amh $((2*$amt+$amh+10))  $isrb
./go_command $amt $amh $((2*$amt+$amh+20))  $isrb
./go_command $amt $amh $((2*$amt+$amh+30))  $isrb
./go_command $amt $amh $((2*$amt+$amh+40))  $isrb
./go_command $amt $amh $((2*$amt+$amh+60))  $isrb
./go_command $amt $amh $((2*$amt+$amh+80))  $isrb
./go_command $amt $amh $((2*$amt+$amh+110))  $isrb
./go_command $amt $amh $((2*$amt+$amh+130))  $isrb
./go_command $amt $amh $((2*$amt+$amh+160))  $isrb
./go_command $amt $amh $((2*$amt+$amh+210))  $isrb
./go_command $amt $amh $((2*$amt+$amh+260))  $isrb
./go_command $amt $amh $((2*$amt+$amh+360))  $isrb
./go_command $amt $amh $((2*$amt+$amh+460))  $isrb
./go_command $amt $amh $((2*$amt+$amh+560))  $isrb
echo "plot" >> integ.dat
echo "join" >> integ.dat
#--
#  Start bases.
#    for m_H = 120
#--
amh=120
echo "(  $title" >> integ.dat
echo "(  isrb = $isrb" >> integ.dat
echo "(  sqrts	sigma	    error	m_t	     m_H" >> integ.dat
echo "(-----------------------------------------------------------" >> integ.dat
echo "(  m_H = $amh" >> integ.dat
./go_command $amt $amh $((2*$amt+$amh+1))  $isrb
./go_command $amt $amh $((2*$amt+$amh+5))  $isrb
./go_command $amt $amh $((2*$amt+$amh+10))  $isrb
./go_command $amt $amh $((2*$amt+$amh+20))  $isrb
./go_command $amt $amh $((2*$amt+$amh+30))  $isrb
./go_command $amt $amh $((2*$amt+$amh+40))  $isrb
./go_command $amt $amh $((2*$amt+$amh+60))  $isrb
./go_command $amt $amh $((2*$amt+$amh+80))  $isrb
./go_command $amt $amh $((2*$amt+$amh+100))  $isrb
./go_command $amt $amh $((2*$amt+$amh+120))  $isrb
./go_command $amt $amh $((2*$amt+$amh+140))  $isrb
./go_command $amt $amh $((2*$amt+$amh+160))  $isrb
./go_command $amt $amh $((2*$amt+$amh+190))  $isrb
./go_command $amt $amh $((2*$amt+$amh+240))  $isrb
./go_command $amt $amh $((2*$amt+$amh+340))  $isrb
./go_command $amt $amh $((2*$amt+$amh+440))  $isrb
./go_command $amt $amh $((2*$amt+$amh+540))  $isrb
echo "plot" >> integ.dat
echo "join" >> integ.dat
#--
#  Start bases.
#    for m_H = 150
#--
amh=150
echo "(  $title" >> integ.dat
echo "(  isrb = $isrb" >> integ.dat
echo "(  sqrts	sigma	    error	m_t	     m_H" >> integ.dat
echo "(-----------------------------------------------------------" >> integ.dat
echo "(  m_H = $amh" >> integ.dat
./go_command $amt $amh $((2*$amt+$amh+1))  $isrb
./go_command $amt $amh $((2*$amt+$amh+5))  $isrb
./go_command $amt $amh $((2*$amt+$amh+10))  $isrb
./go_command $amt $amh $((2*$amt+$amh+20))  $isrb
./go_command $amt $amh $((2*$amt+$amh+30))  $isrb
./go_command $amt $amh $((2*$amt+$amh+40))  $isrb
./go_command $amt $amh $((2*$amt+$amh+60))  $isrb
./go_command $amt $amh $((2*$amt+$amh+80))  $isrb
./go_command $amt $amh $((2*$amt+$amh+110))  $isrb
./go_command $amt $amh $((2*$amt+$amh+130))  $isrb
./go_command $amt $amh $((2*$amt+$amh+160))  $isrb
./go_command $amt $amh $((2*$amt+$amh+210))  $isrb
./go_command $amt $amh $((2*$amt+$amh+260))  $isrb
./go_command $amt $amh $((2*$amt+$amh+310))  $isrb
./go_command $amt $amh $((2*$amt+$amh+410))  $isrb
./go_command $amt $amh $((2*$amt+$amh+510))  $isrb
echo "plot" >> integ.dat
echo "join" >> integ.dat

exit 0
