C--
C  Kinematical variables for spring.
C--
      COMMON/KINEMS/IBX,IBCOS,FUNCZ(2,2),
     .              OMEGA1,AK1,COSTH1,SINTH1,
     .              OMEGA2,AK2,COSTH2,SINTH2,COSPH2,SINPH2,
     .              OMEGAZ(2,2),AKZ(2,2),COSTHZ(2),SINTHZ(2),
     .              COSPHI,SINPHI
C--
      REAL*8        IBX,IBCOS,FUNCZ,
     .              OMEGA1,AK1,COSTH1,SINTH1,
     .              OMEGA2,AK2,COSTH2,SINTH2,COSPH2,SINPH2,
     .              OMEGAZ,AKZ,COSTHZ,SINTHZ,COSPHI,SINPHI
