C--
C  Kinematical variables used for amplitude calculations.
C--
      COMMON/KINEM2/S12,S22,S1S2,S1Q1,S1Q2,S2Q1,S2Q2,S1P2,S1P3,
     .              S2P1,S2P3,P1P2,P1P3,P2P3,P3Q1,P3Q2,Q12,Q22,Q32,
     .              P1Q2,P2Q1,S1P1,S2P2
C--
      REAL*8        S12,S22,S1S2,S1Q1,S1Q2,S2Q1,S2Q2,S1P2,S1P3,
     .              S2P1,S2P3,P1P2,P1P3,P2P3,P3Q1,P3Q2,Q12,Q22,Q32,
     .              P1Q2,P2Q1,S1P1,S2P2
